### ISSUE TITLE
Not enough DNA test results to issue a prediction at "today"

### ISSUE THREAD

**Issue by giadasp** [Chicago/clear-water-app#7]
Dear Tom Schenk Jr,
I'm sorry if I'm asking something obvious but I'm a freshman in programming and I'm encountering 2 different problems in Running the app.R code (Run with sys.time=2017-11-18 12:43:00"):

1. The `datasetUrl ` value "https://data.cityofchicago.org/Parks-Recreation/Beach-Lab-Data/2ivx-z93u/data" gives the error 403, so I changed this value to "https://data.cityofchicago.org/api/views/2ivx-z93u/rows.csv?accessType=DOWNLOAD" and then I'm able to assign the datatable to `labPortal`. Have I done the right thing?

2. Then I tried to generate predictions but the variable `readyToModel ` is FALSE and so I'm not able to perform the predictions. So I tried to change the `today` value to an old date (such as may 2017) but `readyToModel ` is still FALSE.

What I can do to solve these issues?
Thank you

Giada

**Comment by nicklucius** [comment]
Hi @giadasp, I've taken a look at this issue and I wonder if you've tried the `datasetURL` from the [code](https://github.com/Chicago/clear-water-app/blob/master/app.R#L37), which is "https://data.cityofchicago.org/Parks-Recreation/Beach-Lab-Data/2ivx-z93u". The URL in your comment above has `/data` appended to it. 

There is an [open issue](https://github.com/Chicago/RSocrata/issues/147) in `RSocrata` about the `/data` issue. As it stands currently, `read.socrata()` supports the URL that takes you to the "landing page" of the actual dataset, but does not support the "grid view" (e.g., `/data`) URL.

Once you get past the 403 error, make sure you use a value for `today` which has the prerequisite DNA test results [here](https://data.cityofchicago.org/Parks-Recreation/Beach-Lab-Data-DNA-Tests/hmqm-anjq/data), such as 9/4/2017.

**Comment by giadasp** [comment]
1.If I remember well I tried also without '/data' but it didn'twork as well

2. I tried with 9/4/2017 and I had some predictions but I couldn't be able to upload them compiling all the code.

**Comment by nicklucius** [comment]
Ok I see. If you could post the code where you're getting the error, I can take a look.
